[build]
  command = "curl -o master.zip https://codeload.github.com/guidoline/guidoline.com-content/zip/master && unzip master.zip && mv guidoline.com-content-master content && yarn && yarn run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "production"
