---
new_page_extension: md
auto_deploy: false
admin_path: public/admin
webhook_url: 
sections:
- type: document
  path: content/index.md
  label: Accueil
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - journal-event
  - journal-article
  - journal-information
  - journal-story
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
  templates:
  - page
- type: document
  path: content/a-propos.md
  label: À propos
- type: heading
  label: Sections
- type: directory
  path: content/authors
  label: Authors
  create: documents
  match: "**/*"
  templates:
  - auteur
- type: heading
  label: Configuration
- type: document
  path: content/settings/global.json
  label: Paramètres
- type: document
  path: content/settings/navigation.json
  label: Navigation
upload_dir: public/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: "./"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
