---
new_page_extension: md
auto_deploy: false
admin_path: public/admin
webhook_url: 
sections:
- type: document
  path: content/welcome.mdk
  label: Accueil
- type: directory
  path: content/journal
  label: Journal
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
  templates:
  - page
- type: heading
  label: Sections
- type: directory
  path: content/authors
  label: Authors
  create: documents
  match: "**/*"
  templates:
  - auteur
- type: heading
  label: Configuration
- type: document
  path: content/settings/global.json
  label: Paramètres
- type: document
  path: content/settings/navigation.json
  label: Navigation
upload_dir: public/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: true
file_template: ":year:/:month:/:filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
