---
label: configuration.global
hide_body: true
fields:
- type: text
  name: name
  label: name
- type: text
  name: description
  label: description
- type: textarea
  name: about
  label: about
- type: field_group
  name: contacts
  label: contacts
  fields:
  - type: field_group
    name: main
    label: Principal
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: description
      label: description
    - type: field_group
      name: address
      label: address
      fields:
      - type: text
        name: name
        label: name
      - type: text
        name: street
        label: street
      - type: text
        name: zipcode
        label: zipcode
      - type: text
        name: city
        label: city
      - type: text
        name: country
        label: country
    - type: text
      name: email
      label: email
    - type: text
      name: phone
      label: phone
    - type: text
      name: hours
      label: hours
  - type: field_group
    name: secondary
    label: Secondaire
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: description
      label: description
    - type: field_group
      name: address
      label: address
      fields:
      - type: text
        name: name
        label: name
      - type: text
        name: street
        label: street
      - type: text
        name: zipcode
        label: zipcode
      - type: text
        name: city
        label: city
      - type: text
        name: country
        label: country
    - type: text
      name: email
      label: email
    - type: text
      name: phone
      label: phone
    - type: text
      name: hours
      label: hours
- type: text
  name: credits
  label: credits
- type: list
  name: categories
  label: categories
- type: text
  name: url
  label: url
- name: journal
  type: field_group
  config: {}
  fields:
  - name: categories
    type: list
    config:
      use_select: false
      min: 
      max: 
      source:
        type: simple
    label: Catégories
  - name: articles_per_page
    type: number
    label: Articles par page
    description: ''
    default: 25
    required: true
    config:
      min: 5
      max: 60
      step: 
  label: Journal
pages:
- content/settings/global.json
