---
label: configuration.global
hide_body: true
fields:
- type: text
  name: url
  label: url
- type: text
  name: name
  label: Nom
- type: text
  name: description
  label: Description
- type: textarea
  name: about
  label: À propos
  config:
    wysiwyg: true
    schema:
      format: html-blocks
- type: text
  name: credits
  label: Crédits
- type: field_group
  name: contacts
  label: Contacts
  fields:
  - type: field_group
    name: main
    label: Principal
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: description
      label: description
    - type: field_group
      name: address
      label: address
      fields:
      - type: text
        name: name
        label: name
      - type: text
        name: street
        label: street
      - type: text
        name: zipcode
        label: zipcode
      - type: text
        name: city
        label: city
      - type: text
        name: country
        label: country
    - type: text
      name: email
      label: email
    - type: text
      name: phone
      label: phone
    - type: text
      name: hours
      label: hours
  - type: field_group
    name: secondary
    label: Secondaire
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: description
      label: description
    - type: field_group
      name: address
      label: address
      fields:
      - type: text
        name: name
        label: name
      - type: text
        name: street
        label: street
      - type: text
        name: zipcode
        label: zipcode
      - type: text
        name: city
        label: city
      - type: text
        name: country
        label: country
    - type: text
      name: email
      label: email
    - type: text
      name: phone
      label: phone
    - type: text
      name: hours
      label: hours
- name: journal
  type: field_group
  config: {}
  fields:
  - name: categories
    type: tag_list
    default: []
    label: Catégories
  - name: articles_per_page
    type: number
    label: Articles par page
    description: ''
    default: 25
    required: true
    config:
      min: 5
      max: 60
      step: 
  label: Journal
- name: socials
  type: field_group
  config: {}
  fields:
  - name: socials
    type: field_group_list
    fields:
    - name: name
      type: text
      config:
        required: true
      label: Nom
    - name: link
      type: text
      config:
        required: true
      label: Lien
    config:
      min: 
      max: 3
      labelField: name
    label: Socials
  label: Socials
  description: Liens vers les réseaux sociaux affiché sous forme d'icônes.
pages:
- content/settings/global.json
