---
label: configuration.global
hide_body: true
fields:
- type: text
  name: url
  label: url
- type: text
  name: name
  label: Nom
- type: text
  name: description
  label: Description
- type: textarea
  name: about
  label: À propos
  config:
    wysiwyg: true
    schema:
      format: html-blocks
- type: text
  name: credits
  label: Crédits
- type: field_group
  name: contacts
  label: Contacts
  fields:
  - type: field_group
    name: main
    label: Principal
    fields:
    - type: text
      name: name
      label: Nom
    - type: text
      name: description
      label: Description
    - type: field_group
      name: address
      label: Addresse postale
      fields:
      - type: text
        name: name
        label: Nom du lieu
      - type: text
        name: street
        label: Rue
      - type: text
        name: zipcode
        label: Code postal
      - type: text
        name: city
        label: Ville
      - type: text
        name: country
        label: Pays
    - type: text
      name: email
      label: Email
    - type: text
      name: phone
      label: Téléphone
    - type: text
      name: hours
      label: Horaires
  - type: field_group
    name: secondary
    label: Secondaire
    fields:
    - type: text
      name: name
      label: Nom
    - type: text
      name: description
      label: Description
    - type: field_group
      name: address
      label: Adresse postale
      fields:
      - type: text
        name: name
        label: Nom du lieu
      - type: text
        name: street
        label: Rue
      - type: text
        name: zipcode
        label: Code postal
      - type: text
        name: city
        label: Ville
      - type: text
        name: country
        label: Pays
    - type: text
      name: email
      label: Email
    - type: text
      name: phone
      label: Téléphone
    - type: text
      name: hours
      label: Horaires
  description: Diverse coordonnées à afficher sur le site.
- name: blog
  type: field_group
  config: {}
  fields:
  - name: categories
    type: tag_list
    default: []
    label: Catégories
    description: Les catégories vous permettrons de classez les publications du blog.
      la présentation des articles peuvent être basé sur le nom de la catégorie.
  - name: articles_per_page
    type: number
    label: Articles par page
    default: 25
    required: true
    config:
      min: 5
      max: 60
      step:
    description: Configuration de la pagination de la page d'index du Blog.
  label: Blog
  description: Options pour le blog.
- name: socials
  type: field_group
  config: {}
  fields:
  - name: socials
    type: field_group_list
    fields:
    - name: name
      type: text
      config:
        required: true
      label: Nom
      description: L'icône affiché sera basé sur le nom du réseau social.
    - name: link
      type: text
      config:
        required: true
      label: Lien
    - name: description
      type: text
      config:
        required: false
      label: Description
      description: Par ex. "Consultez nos dernières actualités sur Facebook."
    config:
      min:
      max: 3
      labelField: name
    label: Socials
    description: Vous pouvez ajouter jusqu'à 3 réseaux sociaux.
  label: Socials
  description: Liens vers les réseaux sociaux affiché sous forme d'icônes.
pages:
- content/settings/global.json
