name: CD

on: [push]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Get content
      uses: actions/checkout@v2
      with:
        repository: guidoline/guidoline.com-content
        path: content
        lfs: true
    - name: Install npm dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: GitHub Pages Deploy
      if: success()
      uses: maxheld83/ghpages@v0.2.1
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PATH }}
